spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: payment_user
    password: payment_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080

# Mock toggles
app:
  mock-kafka: true
  mock-redis: true
